# Generated by Django 4.2.3 on 2023-07-22 01:37

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-date_created']},
        ),
        migrations.RenameField(
            model_name='account',
            old_name='date_opened',
            new_name='date_created',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=13, prefix='kez'),
        ),
    ]
