# Generated by Django 4.2.3 on 2023-07-22 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_kyc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc',
            old_name='image',
            new_name='identity_image',
        ),
        migrations.AddField(
            model_name='kyc',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='signature',
            field=models.ImageField(blank=True, upload_to='kyc'),
        ),
    ]
