# Generated by Django 4.2.3 on 2023-07-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_image_kyc_identity_image_kyc_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='address',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='full_name',
        ),
        migrations.AddField(
            model_name='kyc',
            name='firstname',
            field=models.CharField(default='John', max_length=100),
        ),
        migrations.AddField(
            model_name='kyc',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='kyc'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='lastname',
            field=models.CharField(default='Doe', max_length=100),
        ),
        migrations.AddField(
            model_name='kyc',
            name='state',
            field=models.CharField(default='Lagos', max_length=150),
        ),
        migrations.AddField(
            model_name='kyc',
            name='street',
            field=models.CharField(default='21 Awolowo way', max_length=150),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='city',
            field=models.CharField(default='Ikeja', max_length=100),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('other', 'Other')], default='single', max_length=15),
        ),
    ]
