# Generated by Django 4.2.3 on 2023-07-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_kyc_address_remove_kyc_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='firstname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='lastname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='state',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='street',
            field=models.CharField(max_length=150),
        ),
    ]
