# Generated by Django 4.2.3 on 2023-07-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_kyc_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='gender',
            field=models.CharField(choices=[('None', 'Select Gender'), ('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=15),
        ),
    ]
