# Generated by Django 4.2.3 on 2023-07-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_kyc_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='country',
            field=models.CharField(choices=[(None, ''), ('NG', 'Nigeria'), ('GH', 'Ghana'), ('US', 'United States of America')], default='ng', max_length=100),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='gender',
            field=models.CharField(choices=[(None, ''), ('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=15),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='identity_type',
            field=models.CharField(choices=[(None, ''), ('national_id', 'National ID Card'), ('drivers_licence', 'Drivers Licence'), ('international_passport', 'International Passport')], default='drivers_licence', max_length=100),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='marital_status',
            field=models.CharField(choices=[(None, ''), ('single', 'Single'), ('married', 'Married'), ('other', 'Other')], default='single', max_length=15),
        ),
    ]
