# Generated by Django 4.2.3 on 2023-07-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_kyc_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='identity_type',
            field=models.CharField(choices=[(None, ''), ('national_id', 'National ID Card'), ('drivers_licence', 'Drivers Licence'), ('international_passport', 'International Passport')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='marital_status',
            field=models.CharField(choices=[(None, ''), ('single', 'Single'), ('married', 'Married'), ('other', 'Other')], default='', max_length=15),
        ),
    ]
