# Generated by Django 4.2.3 on 2023-07-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_kyc_identity_type_alter_kyc_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='gender',
            field=models.CharField(choices=[(None, ''), ('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', error_messages={'required': 'Required'}, max_length=15),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='image',
            field=models.ImageField(default='default.jpg', error_messages={'required': 'Required'}, upload_to='kyc'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='marital_status',
            field=models.CharField(choices=[(None, ''), ('single', 'Single'), ('married', 'Married'), ('other', 'Other')], default='', error_messages={'required': 'Required'}, max_length=15),
        ),
    ]
