# Generated by Django 4.2.3 on 2024-11-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_kyc_gender_alter_kyc_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='inactive', max_length=100),
        ),
    ]
